### ISSUE TITLE
Couldn't get into "editing" Modal to edit Stock Name and Comment on StocktakeEdit Page 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2308]
## Describe the bug

There is a bug stop user editing Stocktake Name and comment on StocktakeEdit page

### To reproduce

1. Go to 'Stocktake page'
2. Click on ' Stocktake Name'
3. Click on editing button next to Stocktake Name and Comment

### Expected behaviour

An editing Modal should pop-up for user to edit stocktake name and to make comments 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v4.0.0 rc-1
- Tablet model: Samsung
- OS version:

**Comment by joshxg** [comment]
@Rebecca367 

I can't reproduce this. Are there any more details you can provide?

**Comment by joshxg** [comment]
@Rebecca367 

Are you able to reproduce this on RC12?

**Comment by joshxg** [comment]
@Rebecca367 

Can you check on this again please? I cannot recreate that

**Comment by bijaySussol** [comment]
@Rebecca367 @joshxg : 

Tested this with v4.0.0RC14 APK on:
Tablet name: Samsung
Type: Andriod 4.4.4

I could not see any issue with this.
As this was raised against this version `v4.0.0 rc-1` maybe it is fixed by now.
I can test on `v4.0.0 rc-1` if this is really needed.

But, I don't see any issue on this version APK: `v4.0.0RC14`

**Comment by anildahalsussol** [comment]
Still it can be re-created haha.... i can show on Monday...

**Comment by Rebecca367** [comment]
@joshxg 
As discussed, this bug still remain in rc15 as it was shown to you before.

**Comment by Rebecca367** [comment]
please refer to issue #2430  that the issue has been fixed, so I will close the issue now. FYR

**Comment by bijaySussol** [comment]
> Still it can be re-created haha.... i can show on Monday...
> 
> ![Screenshot 2020-02-28 at 18 04 28](https://user-images.githubusercontent.com/18479204/75548232-e0978300-5a54-11ea-9c3e-808f4e7a2f4b.png)

@anildahalsussol : 

As seen this morning on my test data file with the same setting - Still, we ain't able to see this issue - which made me think - could be to do with the data file.
Anyway, Looks like @joshxg now have found the reason for the problem and fixed it.

**Comment by joshxg** [comment]
Oops!!!!

Sorry - yes - it has occurred because of REASONS for the stocktake...!!!!
